### ISSUE TITLE
Script/extension not showing up in Fiddler

### ISSUE THREAD

**Issue by BenMorales82** [cppisking/ffrk-inspector#2]
I have pretty much everything set up correctly except for the scripts. I downloaded the dll files, copied them to the specified documents folder, and restarted Fiddler. I don't see the FFRK tab anywhere. Unless I'm looking in the wrong place. I see a tab called "inspectors", but that seems to be for something else. I checked the dll files to make sure they are unblocked as well. Running on a Windows 7 machine.

**Comment by bqlohr** [comment]
I have the same issue.  Fiddler is v4.5.1.0, .NET is 4.5.2.  See screens:

http://i.imgur.com/tLn4pCH.png
http://i.imgur.com/lZF5bhL.png

**Comment by bqlohr** [comment]
Oops, here's scripts in the right place:

http://i.imgur.com/73E3CQT.png

**Comment by cppisking** [comment]
Can you post a screenshot of Fiddler > Options > HTTPS?

Also in the Quick Command box (bottom left corner, below the list where you see all the *Tunneling to* commands), type the following:

prefs set fiddler.debug.extensions.showerrors True
prefs set fiddler.debug.extensions.verbose True

Then close and restart Fiddler, and post any error messages you see)

**Comment by bqlohr** [comment]
http://imgur.com/2xTB0eC
http://imgur.com/68MlCYL
http://imgur.com/gokJKiv

Haven't begun HTTPS setup yet so that is still unchecked.

**Comment by bqlohr** [comment]
Ugh, terribly embarrassing - I saved the file links as the files themselves so just didn't have the .dll/etc downloaded properly.  

Downloaded the files correctly and now it's loading fine.  Apologies for the thrash.

**Comment by cppisking** [comment]
No worries.  If I had more time I would have made an installer so people didn't have to jump through all these hoops.  Glad you got it working though

**Comment by leocristo28** [comment]
my fiddler somehow refuse to load the ffrkI, here's the SS of the error and the files in the right location:
http://imgur.com/t5fLqB5

**Comment by cppisking** [comment]
If you go to Help -> About Fiddler, can you post a screenshot of that?

**Comment by leocristo28** [comment]
oh my silly, never mind my .net is outdated. updated and it's working just fine now. sorry for the troubles >_<
