### ISSUE TITLE
Feature Request: Minimum Times Run Search Parameter

### ISSUE THREAD

**Issue by Rodze** [cppisking/ffrk-inspector#30]
It would be nice if we could filter the Item Search by times run.

Example: I want only to see the battles that have been tried more than 10 times.

**Comment by Endracion** [comment]
A quick export to csv button could help in a lot of this stuff, where you could just trow it in excel and play with the data really quickly. It would be twice as useful for posting stuff back on Reddit with graphs, percentage tables, etc.

**Comment by cppisking** [comment]
I'll probably add exporting to CSV in the next release along with a couple other enhancements.  See #8, which basically is the tracking issue for exporting fields.

**Comment by cppisking** [comment]
Both of these (minimum times run and export to CSV) are done and will be in the next release.
