### ISSUE TITLE
[Bug report] Infinite loading loop.

### ISSUE THREAD

**Issue by lexaduna** [cppisking/ffrk-inspector#40]
I want to report a bug. I did exacly what you said in readme to configure fiddler on android. Fiddler intercepted traffic from android device, proxy working and i can browse internet and see http://ipv4.fiddler:8888/ which means that it should work just fine. I can even play hearthstone via proxy.
However, when i'm trying to connect to Record Keeper the game stuck as if you have bad connection and trying keep loading. Fiddler log window shows this http://i.imgur.com/AnIhBpt.png and it keeps loading. I manage to make it working with drony as described in this post on reddit.
It seems like 127.0.0.1 causing this issue for me, i tried to add this address as "not use proxy for it" but it didn't help.

Also can you please add to FAQ/readme that there is addition plugin which should be installed to fiddler? "CertMaker for iOS and Android"  http://www.telerik.com/docs/default-source/fiddler/addons/fiddlercertmaker.exe?sfvrsn=2 I couldnt make fiddler intercept traffic without that plugin.

**Comment by cppisking** [comment]
I'm still a little confused about Android, because others have said that it only works *without* the plugin ([reference](http://www.reddit.com/r/FFRecordKeeper/comments/381z2g/ffrk_inspector_is_ready_go_easy_on_me/crryoyg?context=3)) so I'm still not sure what the correct "one size fits all" installation procedure is.

**Comment by karryt** [comment]
Are you sure you added 127.0.0.1 to the list properly? I posted a quick set of screenshots (http://imgur.com/a/U2qC3) for setting up Fiddler (sans FFRK Inspector plugin) a bit back, and at least on vanilla 5.0.1 on Nexus 5/7 all you need to set on the device is the proxy address, port 8888, make sure 127.0.0.1 is set to bypass (you shouldn't see those entries show up at all in Fiddler), and install the self-signed root cert that Fiddler generates.

**Comment by lexaduna** [comment]
Yes i'm sure. I put 127.0.0.1 at "Dont use proxy for" tab, at wifi settings where you set up Host name and port. I dont know other way to list it as exception. Not sure why is this still coming through, unless i use drony.

**Comment by karryt** [comment]
Hmm, so even after listing 127.0.0.1 you are seeing the 127.0.0.1 entries in Fiddler from FFRK? What device and version of Android are you running? Perhaps the vendor broke those settings.

**Comment by meowykyun** [comment]
^ That worked for me, bypassing 127.0.0.1 on the wi-fi proxy, instead of on
drony. Works perfectly now 10/10.

On Mon, Jun 1, 2015 at 4:56 PM, karryt <notifications@github.com> wrote:

> Are you sure you added 127.0.0.1 to the list properly? I posted a quick
> set of screenshots (http://imgur.com/a/U2qC3) for setting up Fiddler
> (sans FFRK Inspector plugin) a bit back, and at least on vanilla 5.0.1 on
> Nexus 5/7 all you need to set on the device is the proxy address, port
> 8888, make sure 127.0.0.1 is set to bypass (you shouldn't see those entries
> show up at all in Fiddler), and install the self-signed root cert that
> Fiddler generates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cppisking/ffrk-inspector/issues/40#issuecomment-107686516>
> .
>



-- 
Marcelo Guedes

**Comment by lexaduna** [comment]
I'm using Sony Xperia Z1Compact, android 5.0.2

**Comment by notalltogether** [comment]
i am having the same problem.  put 127.0.0.1 on bypass, but it still shows up in fiddler. i am also on 5.0.2.

**Comment by karryt** [comment]
On an Xperia device also, notalltogether? Maybe all Xperia devices will need to use drony as a workaround. Did you also need to use that certmaker plugin? On the stock Nexus I was able to use whatever the base Fiddler install includes to generate the Root Certificate.

**Comment by cppisking** [comment]
@karryt Since you've been helping a bunch with Android support issues, would you be willing to write up a guide for configuring Fiddler for Android?

**Comment by karryt** [comment]
I'm dual booting 8.1 and 10 preview on my laptop. I have everything set up on 8.1, I'll set it up again on 10 and try to screenshot everything and put it together in a little nicer format than the series of pics I posted to Reddit earlier. Maybe I'll try to capture some images from my wife's iPad too, never play on it but have the game loaded as a backup and for gem purchases as iTunes credit is easier to find at a discount that Google Play.

**Comment by SkyfireX** [comment]
Hi there, Just wondering was there some data lost? Yesterday I remember doing some runs in Heroic stage 1 and 2 of The Pulse Fal'Cie, but today all the data seems to be missing. Would not be good if this occurs on other levels too.

**Comment by cppisking** [comment]
Check the wordpress blog, i posted about it there

**Comment by truepsyche** [comment]
Super late to the party, thought I'd add my experiences.  I'm playing on a Nexus 5 running Android 5.1.1 (was 5.1 when first installed and working).  I followed all of the recommended Fiddler install instructions including the certificate and was initially experiencing the infinite load loop in FFRK with traffic visible in Fiddler.  Installed Drony and followed the configuration [instructions] (http://www.reddit.com/r/FFRecordKeeper/comments/35x6nq/introducing_ffrk_inspector_and_looking_for_alpha/cr9gz5n) to direct traffic by rule and FFRK:I has been working perfectly since.

As for Bluestacks, my understanding is that it doesn't have the capability to run through a proxy (doesn't have a settings entry for proxy).  I've experienced success with Droid4x, however, using the same method as above.  Presently running Windows 7 on desktop.

**Comment by karryt** [comment]
Hmm, wonder what the difference is between 5.0.1 and 5.1.1. I'll try to update one of my Nexus 7's or my Nexus 5 to the latest release and re-setup. I did get screenshots of the straight basic setup for both Android and iOS, just need to get some screenshots for the Fiddler install and I'll put a doc together. For iOS, I did not need to install the alternate certificate generator that the Fiddler documentation suggested, just browsed to their internal page and clicked the link to install. Found that that's the easiest way to install it for Android too, I didn't realize it started up the internal page at first so was transferring the .cer file via OneDrive.

**Comment by aoshiwik** [comment]
bypassing 127.0.0.1 on the android wi-fi proxy worked for me

**Comment by karryt** [comment]
Long overdue, but I made a first pass at writing up some setup docs for Fiddler and for Android/iOS setup. I'm going to see if I can add in some additional info on various Android emulators and some troubleshooting steps.

https://www.dropbox.com/s/ypqlouzb8g78r51/Setting%20up%20FFRK%20Inspector.pdf?dl=0

**Comment by cppisking** [comment]
This is awesome.  What tool did you use to create the PDF?  Is it possible
to have just the source of the PDF so that it can be modified / updated as
needed?

**Comment by cppisking** [comment]
Alternatively, looking over it, I think this could all be done in Github
markup.  Wouldn't look quite as nice though, what do you think is best?  It
needs to be updateable by at least myself, but preferably anyone with
access to the Github repo so other people can submit patches to the
documentation if they want.

**Comment by karryt** [comment]
Yes of course, I was wondering if I should do it in some other format, I can rework it in GitHub markup if it's specific to GH. Right now it's just a Word doc that I saved as PDF.

**Comment by cppisking** [comment]
If you want to do it in Github markup then feel free to just fork my repo,
edit the README it in your fork, and create a pull request.  BTW, you
didn't mention the Certificate Maker plugin for iOS.  Did you find it to be
unnecessary or did you just leave it out on accident?

**Comment by karryt** [comment]
I decided to try it without using that plugin since it was already setup for my Android devices and it seems to work fine, at least for my one device. I'll work on getting it converted in to GitHub, guess I'll start by learning about forking and pull requests :)

**Comment by cppisking** [comment]
It's pretty simple.  Just click Fork in the top right.  It'll make a
private copy of the repo under your account.  From there go edit the README
(click on it in the file list and then you can edit it in place since it's
a simple text file).  Once you've got it looking good there's a button on
the main page that says Create Pull Request.  That's all there is to it.

**Comment by karryt** [comment]
Okay I think I've got a handle on the basic markdown for GH, will work on it over next day or two and if it ends up being too unwieldy in the readme, maybe we can move it to the project wiki.

**Comment by cppisking** [comment]
Seems like the original poster's issue is solved by bypassing the 127.0.0.1.  Combined with the new documentation being written up, seems ok to close this issue.  If the OP or anyone else still encounters this issue, feel free to re-open.  If you have questions about the documentation or anything, maybe create a new issue with a name that has something to do with documentation, easier to track (and search for) in the future that way
