### ISSUE TITLE
FFRK Not showing up in Fiddler

### ISSUE THREAD

**Issue by bqlohr** [cppisking/ffrk-inspector#41]
Fiddler is v4.5.1.0, .NET is 4.5.2. See screens:

http://i.imgur.com/tLn4pCH.png
http://i.imgur.com/lZF5bhL.png
http://i.imgur.com/73E3CQT.png

Sorry added comment to a previously closed issue.

**Comment by oniled** [comment]
I'm going to assume you installed the MySQL connector for .NET?

https://dev.mysql.com/downloads/connector/net/

Also would you close and restart Fiddler?  Everything else looks correct to get the tab to show up...

**Comment by bqlohr** [comment]
This was resolved on a different issue, the problem was that I saved the wrong script files (saved the link as a file rather than the actual .dll file)
