### ISSUE TITLE
Feature Request: Display drops based on highlighted stage

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#44]
If the user wants to display what drops in a specific stage, he could selected it and only display the relevant drops:

![image](https://cloud.githubusercontent.com/assets/12702990/7923366/7e5df2ee-0880-11e5-98e5-aae8de1d7e93.png)

**Comment by cppisking** [comment]
Yea I've actually had this idea as well.  It would be nice.  See Issue #5.  I'm going to close this issue since it's basically a duplicate of that, but expect to see this feature sometime in the future.
