### ISSUE TITLE
Can't start Record Keeper

### ISSUE THREAD

**Issue by fahrenheitman** [cppisking/ffrk-inspector#46]
After following the setup steps for my Android device, when I try to start RK I get a message stating:
'The page at "https://ffrk.denagames.com" says: An error occurred while loading.'

I believe I followed the steps correctly - Fiddler shows activity from my phone, and I can browse with chrome on my phone fine.  The only difference I see is that the "Certificate generated using: Fiddler.DefaultCertificateProvider" instead of the BCCertmaker from your walkthrough.  However, searching on Fiddler documentation page indicates that the Certmaker plugin is for iOS setup, not Android.

Any thoughts?

**Comment by karryt** [comment]
Did you exempt 127.0.0.1 in the proxy settings? If you see any traffic with that as the destination in Fiddler than the game will not complete loading. Looks like it caches a bit of content which is served from the device.

**Comment by fahrenheitman** [comment]
Forgive me if I'm a bit slow with this stuff- by "exempt 127.0.0.1 in the proxy settings," do you mean on my phone?  As in, should I enter that in for the "Bypass proxy for:"  entry when setting up a manual proxy?  Or should that be set in Fiddler somewhere?  Thanks.

**Comment by karryt** [comment]
Yep, sorry should have been more clear. Put it in the "Bypass proxy for:" entry in the wifi settings of your Android device. Should look similar to this: http://i.imgur.com/z7fa1Px.jpg

**Comment by fahrenheitman** [comment]
Fantastic, everything is working now.  Thanks for your help!
