### ISSUE TITLE
Item Database > Adding equipment_id when it isn't provided

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#51]
In order to add an item, you need to provide the equipment ID as part of the first 6 required fields.
The help text mentions finding the equipment ID in the Inventory tab, but it isn't actually provided there.
This mean that there's no way for us to send/update new item information.

**Comment by cppisking** [comment]
Thanks, you're right this needs to be fixed.

**Comment by cppisking** [comment]
This is fixed locally, and will be in the next release.  Thanks for reporting it!
