### ISSUE TITLE
Random Vector dungeon popping up under Daily Dungeon Item search

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#52]
Disregard this, it was just a display error, it doesn't always refresh properly.

**Comment by cppisking** [comment]
Currently search by area requires you to make a selection in each of the 3
boxes. Actually the first two boxes are totally ignored, they exist only as
a way to filter down the choices for the 3rd box, which is the only one
that is actually used. I have plans to fix this later
