### ISSUE TITLE
Mislabeled Item - Bronze Helm from different Realm

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#54]
I can't give you the ID since I don't have access to it, but it's coming up as Bronze Helm (II), when it's actually the Bronze Helm (V); there are a few items with the same name but different realm RS.

http://i.imgur.com/1nonMwE.png

**Comment by cppisking** [comment]
Is it possible you actually do have multiple Bronze Helm (II)'s? I can't
imagine how this could happen, the item name I print in the grid is the
same as what's sent by the server.

**Comment by Endracion** [comment]
No, I have multiple Bronze Helm (V) - what I'm saying is it's reporting the wrong Bronze Helm. I have 0 Bronze Helm (II)s.

I was saying that other than these Helms, the game has a few items that share the same name, but are actually different and separated by their Realm difference. It was probably unclear from my original post.

**Comment by karryt** [comment]
Are you very sure you don't have both? I have 1++ of both, guess they are both common 1* drops. Try sorting by Type and then scrolling down to the helms.

**Comment by Endracion** [comment]
You know what, I'm crazy, I do have triples of both - I looked it up on the website and I recognize the item thumbnail.

**Comment by cppisking** [comment]
It was clear, it's just that I explicitly handle this case and it's
supposed to be supported. And i thought (although I can't check the code
right now) that the text I print in the name field is exactly what is sent
by the game, which would mean the game is actually sending "Bronze Helm
(II)".

I'll check the code, in the meantime do you mind going to the debugging tab
and selecting the row on the left that says /dff/party/list and sending it
to me? Your account id may be in there somewhere, so you can scrub it
manually before posting here, or just email.

**Comment by cppisking** [comment]
Haha ok i was worried i was going crazy :). Cheers
