### ISSUE TITLE
On the Inventory tab, add an option for "at the maximum rarity that can be achieved only by combining existing equipment"

### ISSUE THREAD

**Issue by cppisking** [cppisking/ffrk-inspector#57]
Basically, some items are really hard to get.  If you have only 1 of the items then "current rarity maximum level" is useful, and if you plan to eventually get 3 of the item, or you have 3 already then "maximum rarity and maximum level" is useful., But if you only have 2, you may still want to know what it's going to look like after you upgrade it as much as possible using your existing materials.

**Comment by Endracion** [comment]
Not sure how complex this is to code, but I would really enjoy such a feature - it helps in deciding if I'm going to spend materials to level something up or if it's actually worse than what I already have.

Right now I flip between max stats and current stats and try to figure it out that way, but if it could automatically tell me what the max is given how many times I can currently combine it, it would be amazing.

**Comment by cppisking** [comment]
I already have this working in my local build, but it doesn't work for
computing the score, only viewing stats. Still better than nothing. Should
be in the next release

**Comment by Endracion** [comment]
Score is just the cherry on top, stats are the most important, so it's awesome if it's working already!

When are you planning on pushing the next build? In time for the awesome new patch?

**Comment by cppisking** [comment]
Maybe, I've been kind of slacking. Certainly before next Friday though,
because then I'm leaving the country for 5 minutes and won't be able to put
out further updates until I'm back :-/

**Comment by cppisking** [comment]
Err, 5 weeks. Lol. Not sure where minutes came from

**Comment by karryt** [comment]
Haha, was thinking 5 minutes...so stepping in to Canada or Mexico to grab a soda or something?

**Comment by cppisking** [comment]
This is done, should be in the next release later this week
