### ISSUE TITLE
Log drops at start of battle, rather than after it ends.

### ISSUE THREAD

**Issue by Fat-Chocobo** [cppisking/ffrk-inspector#58]
From what I gather, the drops are only logged once the battle actually ends - but wouldn't it be possible (and probably preferable) to log the drops as soon as the fight begins? 

By doing this we'd get much more data on droprates in the cases where people use the airplane trick to flee from fights when hunting a specific drop.

**Comment by DennisJWheeler** [comment]
With inspector you shouldn't need the airplane trick.  You get the information right once the battle starts, so you can flee immediately.

Also, the data that happens on battle start is the same as resume.  So it would also skew data.  It does however store data on success, flee, etc.  All the calls it can find.

**Comment by Fat-Chocobo** [comment]
The airplane trick is the general name I was giving to leaving the fight before it completes, since it was the most popular method in the past, but if the inspector does indeed log the drops on flee already then this post can be removed.

**Comment by cppisking** [comment]
Drops are logged when you flee also, I don't think this should be an issue

**Comment by Fat-Chocobo** [comment]
Thanks, I wasn't aware of this.
