### ISSUE TITLE
Possible Item Search Filter Bug

### ISSUE THREAD

**Issue by Rodze** [cppisking/ffrk-inspector#59]
Steps to reproduce:

Rarity: Three -> Name: lightning orb -> Search
Result: one of them is Vector - Interception with 29 times run.

Rarity: empty -> Name: empty -> World: FF VI -> Dungeon: Vector -> Search
Result: no lightning orb.

**Comment by cppisking** [comment]
So this is currently really confusing, because I don't have a column to
show the world name.  The Vector that's showing a lightning orb is actually
from Locke's event.  Try choosing "The Legendary Plunderer" as the world
and then choosing Vector.

**Comment by Rodze** [comment]
As you answered that, I opened a new issue to add the world column. lol

I had already asked for that in that one long list, but you asked to open individual requests and I ended up forgetting.
