### ISSUE TITLE
Feature Request: Add World to Item Search Results

### ISSUE THREAD

**Issue by Rodze** [cppisking/ffrk-inspector#60]
On the Item Search results, add a column besides Dungeon and Battle, with the world (core, I-XIII, daily, etc.).

I don't really know all dungeons names by memory. =P

**Comment by Endracion** [comment]
It's already there?

http://i.imgur.com/N8woDTI.png

**Comment by Rodze** [comment]
For search results, not search parameters.

**Comment by Rodze** [comment]
This was done, so closing.
