### ISSUE TITLE
Version 2 gives an update error and can't connect to DB

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#63]
On launch:
http://i.imgur.com/6iKRoc4.png

DB window:
http://i.imgur.com/cxUF2ma.png

**Comment by cppisking** [comment]
That is...  really weird.  I wonder if I attached the wrong files to the release.  Let me check

**Comment by cppisking** [comment]
https://github.com/cppisking/ffrk-inspector/blob/master/FFRKInspector.dll

Can you try this?

**Comment by Endracion** [comment]
Yep, no issues with the one you posted now.

**Comment by cppisking** [comment]
Cool, I just updated the release page.  Thanks!
