### ISSUE TITLE
Item Search showing unavailable events

### ISSUE THREAD

**Issue by BaconCatBug** [cppisking/ffrk-inspector#64]
Especially with the "I want to help" filter, it shows a lot of entries from the Fire Powered Ship. These should be removed once the event is finished IMHO, or at least hidden in case the event shows up again.

**Comment by cppisking** [comment]
I will try to come up with a way to do that, but it's not very easy

**Comment by cppisking** [comment]
Seems like this will be possible after all, hopefully I can finish this in time before I leave the country.

**Comment by rsilva712** [comment]
Would a "hide event dungeons" check mark be difficult to implement?

**Comment by cppisking** [comment]
Not really, do you think that would still be useful though if there's already a check box to hide inactive events?  I have that working locally so it'll go out with the next release.  I don't want to clutter up the UI too much though unless you think it will really be useful

**Comment by BaconCatBug** [comment]
I think a box to hide inactive events is more than enough,

**Comment by cppisking** [comment]
This is done, will be available later this week
