### ISSUE TITLE
Fiddler is inspecting FFRK but nothing is displayed in FFRK inspector tab

### ISSUE THREAD

**Issue by Uris-Chan** [cppisking/ffrk-inspector#65]
Tested with browser on Android and it shows the Fiddler MITM certificate.
Fiddler is displaying the JSON data from the HTTP POST in FFRK. However, FFRK Inspector shows that it is connected but no data is shown on the various screen.
Version installed is 2.02
![fiddler web debugger_2015-06-07_11-50-34](https://cloud.githubusercontent.com/assets/12781081/8022564/cb3f201c-0d0b-11e5-918e-7423ef57405c.png)
![fiddler web debugger_2015-06-07_11-51-00](https://cloud.githubusercontent.com/assets/12781081/8022566/cb4160e8-0d0b-11e5-8be3-e410d73deb29.png)
![fiddler web debugger_2015-06-07_11-51-05](https://cloud.githubusercontent.com/assets/12781081/8022565/cb40e4e2-0d0b-11e5-8090-2d972a0043a3.png)
![fiddler web debugger_2015-06-07_11-51-09](https://cloud.githubusercontent.com/assets/12781081/8022567/cb4216a0-0d0b-11e5-93eb-55516ccb56c4.png)

**Comment by cppisking** [comment]
This is really strange. Everything is working, but it looks like Fiddler
just isn't telling my extension about the requests.  In the Quick Exec box
(black box in the middle of the window in your screenshots), can you run
these two commands:

prefs set fiddler.debug.extensions.show True
prefs set fiddler.debug.extensions.verbose True

then stop and restart Fiddler, and paste the output of fiddler's Log
window.  I want to see the start of the log as well as what it says when
you launch FFRK.

Also can you paste the output from the Extensions box in Tools > Fiddler
Options > Extensions?

**Comment by Rodze** [comment]
Uncheck the "Stream" button.

**Comment by cppisking** [comment]
Ahh, that would be great if that worked.  I just looked at the hover-over
text of that button.  What is the purpose of the button?  Like what's the
use case for turning it on versus leaving it off?

**Comment by Uris-Chan** [comment]
Hi,

Logs below. This is from login screen --> dungeon screen --> start of
battle (paused)

-= Fiddler Event Log =-
See http://fiddler2.com/r/?FiddlerLog for details.

13:40:42:3179 Fiddler Running...
13:40:42:3189 Searching for Inspectors under C:\Program Files
(x86)\Fiddler2\Inspectors\
13:40:42:3189 Looking for Inspectors inside C:\Program Files
(x86)\Fiddler2\Inspectors\Standard.dll
13:40:42:3189     Class Standard.AuthChallengeAnalyzer is a Response
inspector.
13:40:42:3189     Class Standard.AuthReplyAnalyzer is a Request inspector.
13:40:42:3189     Class Standard.CachingAnalyzer is a Response inspector.
13:40:42:3189     Class Standard.HexRequestViewer is a Request inspector.
13:40:42:3189     Class Standard.HexResponseViewer is a Response inspector.
13:40:42:3189     Class Standard.ImageViewer is a Response inspector.
13:40:42:3189     Class Standard.JSONRequestViewer is a Request inspector.
13:40:42:3189     Class Standard.JSONResponseViewer is a Response inspector.
13:40:42:3189     Class Standard.RawRequest is a Request inspector.
13:40:42:3189     Class Standard.RawResponse is a Response inspector.
13:40:42:3189     Class Standard.RequestCookieAnalyzer is a Request
inspector.
13:40:42:3189     Class Standard.RequestHeaderView is a Request inspector.
13:40:42:3189     Class Standard.RequestTextViewer is a Request inspector.
13:40:42:3189     Class Standard.RequestWebForm is a Request inspector.
13:40:42:3189     Class Standard.ResponseCookieAnalyzer is a Response
inspector.
13:40:42:3189     Class Standard.ResponseHeaderView is a Response inspector.
13:40:42:3189     Class Standard.ResponseTextViewer is a Response inspector.
13:40:42:3189     Class Standard.ResponseWebView is a Response inspector.
13:40:42:3189     Class Standard.Transformer is a Response inspector.
13:40:42:3189     Class Standard.XMLRequestViewer is a Request inspector.
13:40:42:3189     Class Standard.XMLResponseViewer is a Response inspector.
13:40:42:3189 Searching for Inspectors under
C:\Users\XXX\Documents\Fiddler2\Inspectors\
13:40:42:3189 Searching for FiddlerExtensions under
C:\Users\XXX\Documents\Fiddler2\Scripts\
13:40:42:3189 Searching for FiddlerExtensions under C:\Program Files
(x86)\Fiddler2\Scripts\
13:40:42:3189 Looking for FiddlerExtensions inside C:\Program Files
(x86)\Fiddler2\Scripts\FFRKInspector.dll
13:40:42:3189     Class FFRKInspector.Proxy.FFRKProxy is a IAutoTamper*
extension.
13:40:42:3189 Looking for FiddlerExtensions inside C:\Program Files
(x86)\Fiddler2\Scripts\Geoedge.dll
13:40:42:3189     Class GeoEdge.Geoedge is a IAutoTamper* extension.
13:40:42:3189 Looking for FiddlerExtensions inside C:\Program Files
(x86)\Fiddler2\Scripts\Newtonsoft.Json.dll
13:40:42:3189     ! Assembly does not specify a valid
Fiddler.RequiredVersionAttribute.
13:40:42:3189 Looking for FiddlerExtensions inside C:\Program Files
(x86)\Fiddler2\Scripts\SimpleFilter.dll
13:40:42:3189     Class AutoSaver.AutoSaveExt is a basic IFiddlerExtension.
13:40:42:3189     Class EventLog.EventLog is a basic IFiddlerExtension.
13:40:42:3189     Class HostsFile.HostsFile is a basic IFiddlerExtension.
13:40:42:3189     Class SAZClipboard.SAZClipboardFactory is a basic
IFiddlerExtension.
13:40:42:3189     Class SimpleFilter.SimpleFilter is a IAutoTamper*
extension.
13:40:42:3189 Looking for FiddlerExtensions inside C:\Program Files
(x86)\Fiddler2\Scripts\Timeline.dll
13:40:42:3189     Class Timeline.Timeline is a basic IFiddlerExtension.
13:40:42:3189 FFRKInspector: Database thread waiting for request
13:40:42:3189 FFRKInspector: Database connection state changed.  Old =
Disconnected, new = Connecting
13:40:42:3189 FFRKInspector: Database connection state changed.  Old =
Connecting, new = Connected
13:40:42:3189 FFRKInspector: Database thread dequeued request of type
DbOpVerifySchema
13:40:42:3189 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:42:3979 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:42:6219 FFRKInspector: Database thread waiting for request
13:40:42:6219 FFRKInspector: Database thread dequeued request of type
DbOpLoadAllItems
13:40:42:6219 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:42:8359 FFRKInspector: Database exceuting operation DbOpLoadAllItems
13:40:43:2760 FFRKInspector: Database thread waiting for request
13:40:43:2760 FFRKInspector: Database thread dequeued request of type
DbOpLoadAllBattles
13:40:43:2760 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:43:4900 FFRKInspector: Database exceuting operation DbOpLoadAllBattles
13:40:43:9300 FFRKInspector: Database thread waiting for request
13:40:43:9300 FFRKInspector: Database thread dequeued request of type
DbOpLoadAllDungeons
13:40:43:9300 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:44:1440 FFRKInspector: Database exceuting operation
DbOpLoadAllDungeons
13:40:44:3770 FFRKInspector: Database thread waiting for request
13:40:44:3770 FFRKInspector: Database thread dequeued request of type
DbOpLoadAllWorlds
13:40:44:3770 FFRKInspector: Database exceuting operation DbOpVerifySchema
13:40:44:5920 FFRKInspector: Database exceuting operation DbOpLoadAllWorlds
13:40:44:8230 FFRKInspector: Database thread waiting for request
13:40:51:9905 FFRKInspector: ffrk.denagames.com:443
13:40:52:0185 /Fiddler.CertMaker> Using
Fiddler.DefaultCertificateProvider+CertEnrollEngine for certificate
generation
13:40:53:4965 FFRKInspector: ffrk.denagames.com:443

**Comment by Uris-Chan** [comment]
![fiddler options_2015-06-07_13-43-33](https://cloud.githubusercontent.com/assets/12781081/8022760/6d2c3fa4-0d1b-11e5-9a5c-9ac0a552ae64.png)

**Comment by Uris-Chan** [comment]
Yup. Unchecking the "Stream" button works.

Just curious what does the "Stream" button do hmm

**Comment by Rodze** [comment]
This link explains but I don't really understand: http://fiddlerbook.com/fiddler/help/streaming.asp

It messes up with ffrk-inspector for some reason. I only know because it happened to me.
