### ISSUE TITLE
[Feature Request] Equip Automation

### ISSUE THREAD

**Issue by ipoppo** [cppisking/ffrk-inspector#66]
Is it possible to do automation through API calls? If it is then there are some request feature existing on JP 

- Unequip [Current Party / Other] [Equipment / Ability / RM]
- Optimize equipment base on RS (in case that it still not available)
- Party preset

I didn't look what current optimization done in client or server side, if it is done on client i think it is possible to intercept and submit what we need into server.

**Comment by cppisking** [comment]
It is possible, but I mentioned this in [another thread](https://github.com/cppisking/ffrk-inspector/issues/62), I don't really want to get in the business of issuing API calls to the server.  My principle is "look, but don't touch".  I have to draw the line somewhere as to what constitutes botting and illicit activities, and acting as a 3rd party client for the game kind of crosses that line for me.  Sucks, but we'll just have to wait for the updates to come to NA

**Comment by ipoppo** [comment]
Thanks for clarification
