### ISSUE TITLE
When unknown IDs drop, they aren't added to the dungeon item drops.

### ISSUE THREAD

**Issue by Endracion** [cppisking/ffrk-inspector#70]
Lesser Growth Eggs are now dropping in the Sunday daily, but even though they appear in the Current Battle Drop Anticipation as their ID (no name attached to them atm), once the battle ends, it doesn't seem to be added to the field where all the drops are tallied.

**Comment by cppisking** [comment]
Try again and let me know if you still encounter this problem.  You will
need to stop and restart Fiddler to see the item not show up as a number
anymore.

I reset the run counts of all the daily dungeons back to 0 since these
items weren't getting recorded.

**Comment by Endracion** [comment]
Got it, will report if it works.

Thankfully all daily dungeons changed names, so at least it won't be affecting the other drop tables.

**Comment by cppisking** [comment]
Sadly, it also means we lose statistics for orb drop rates :(

**Comment by Endracion** [comment]
Yeah, that's definitely a bummer :/

Confirmed working: http://i.imgur.com/RaRhTJZ.png
