### ISSUE TITLE
Try to figure out the format of the timestamps in the JSON

### ISSUE THREAD

**Issue by cppisking** [cppisking/ffrk-inspector#72]
A lot of the JSON objects have fields like 'created_at' = '1433811599', and it's not obvious how to interpret this number.  I tried treating it as unix epoch time, windows epoch time, and windows FILETIME, but none of those worked.  

This will be important because in trying to get the "Don't show items from inactive events" checkbox working, some of the events have their info sent to the client even when they're clearly inactive.  But if we could convert the "kept out at" to a timestamp, we could just check if it's later than now.

Some known values that might help figure it out:

1433552399 = The time when Pulse Fal'cie was closed
1433663999 = The time when old Daily Dungeon was disabled
1433664000 = The time when new Daily Dungeon went live
1433682000 = Start time of today (6/7/2005)
1433725200 = The time when Operation Mi'hen starts

It would be interesting to see what "Start time of today" is on consecutive days, that might be the clue to figuring it out.

**Comment by cppisking** [comment]
I have a hack for this that basically just checks if `world`.`kept_out_at` in the JSON is less than `user`.`start_time_of_today` in the /dff/ message that gets sent at program startup.  I'd still like to understand what this value means though, so I'm going ot leave this open.

**Comment by Fat-Chocobo** [comment]
You sure that it's not just Unix epoch time? This website seems to convert them fine for me: http://www.freeformatter.com/epoch-timestamp-to-date-converter.html

**Comment by cppisking** [comment]
Well damn, thanks.  I was pretty sure I tried that (different website though) and it gave me a meaningless number.  Guess this problem is solved :)
