### ISSUE TITLE
Having trouble configuring Fiddler

### ISSUE THREAD

**Issue by nw12digital** [cppisking/ffrk-inspector#80]
I'm trying to set up Fiddler to work with an iOS device. I'm on step 6.(Verify client iOS device can reach Fiddler by navigating in the browser to http://FiddlerMachineIP:8888. This address should return the Fiddler Echo Service page.) I am typing the actual IP that fiddler is giving, but my device is not returning anything when I search for that address. Fiddler is online as I am able to connect to and search the database.

Not sure if it makes a difference, but I am running Windows 8 on a virtual machine hosted on mac OS X yosemite.

**Comment by sordidfellow** [comment]
Did you check out [the Fiddler instructions for running Fiddler in a VM on mac](http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForMac)?

Key "Gotchas" are:
* Network mode must be bridged.
* Fiddler must have remote connections enabled.
* iOS Device must be on same wireless network as the mac that is hosting the fiddler VM.

**Comment by nw12digital** [comment]
Thanks, I hadn't seen or tried that but after setting the network to bridged mode the virtual machine doesn't detect any network connections. I've only had about a half hour to play around with it, I'll have to wait until tomorrow to experiment with it further. Seems odd though that I was able to connect before and changing it to bridged mode sets me back.

**Comment by nw12digital** [comment]
I'm giving up on this for now, I'm still unable to get an internet connection when setting up the virtual machine in bridged mode. Thanks for the help sordidfellow, and everyone else contributing to this great project.
